declare const wx: any;
declare const my: any;
declare const swan: any;
declare const tt: any;
declare const qq: any;
declare const qh: any;
declare const ks: any;
declare const dd: any;
declare const jd: any;
